const OrderStatus = {
  PROCESSING: "PROCESSING",
  APPROVED: "APPROVED",
  PENDING: "PENDING",
  SHIPPED: "SHIPPED",
  SHIPPED_CONFIRMED: "SHIPPED_CONFIRMED",
  DELIVERED: "DELIVERED",
  CANCELLED: "CANCELLED",
  ON_HOLD: "ON_HOLD",
  BACKORDERED: "BACKORDERED",
  REFUNDED: "REFUNDED",
};

export default OrderStatus;
